# 11. 그 밖의 코틀린 기능

## 코틀린 버전 알아내기

```kotlin
// The current Kotlin version is 1.4.0 (주.부.패치)
println("The current Kotlin version is ${KotlinVersion.CURRENT}")
```

## 반복적으로 람다 실행하기

주어진 람다 식을 여러 번 실행하고 싶은 경우 코틀린 내장 repeat 함수를 사용한다.

```kotlin
repeat(5) {
    println("Counting: $it")
}
```

## 완벽한 when 강제하기

코틀린 컴파일러가 when 문에서 가능한 모든 절을 가지도록 강제하게 만들고 싶은 경우 값을 리턴하는 제네릭 타입에 exhaustive라는 확장 속성을 추가하고 when block에 이를 연결한다.

```kotlin
fun printMod3Exhaustive(n: Int) {
    when (n % 3) {
        0 -> println("$n % 3 == 0")
        1 -> println("$n % 3 == 1")
        2 -> println("$n % 3 == 2")
        else -> println("Houston, we have a problem...")
    }.exhaustive
}
```

참고

* [\[Kotlin\] enum/sealed class 그리고 대수적 타입](https://blog.leocat.kr/notes/2020/02/08/kotlin-enum-and-algebraic-data-type)
* [\[kotlin\] safe when statement](https://aroundck.tistory.com/7149)

## 실행 가능한 클래스 만들기

함수를 호출할 클래스에서 invoke 연산자 함수를 재정의한다.

```kotlin
class AstroRequest {
    companion object {
        private const val ASTRO_URL = "http://api.open-notify.org/astros.json"
    }

    operator fun invoke(): AstroResult =
        Gson().fromJson(URL(ASTRO_URL).readText(), AstroResult::class.java)
}

data class AstroResult(
    val message: String,
    val number: Int,
    val people: List<Assignment>
)

data class Assignment(
    val name: String,
    val craft: String
)
```

```kotlin
@Test
fun `get people in space`() {
    // 함수처럼 클래스를 호출(invoke 호출)
    val result = AstroRequest()()
    println(result)
    assertThat(result.message, `is`("success"))
    assertThat(result.number, `is`(greaterThanOrEqualTo(0)))
    assertThat(result.people.size, `is`(result.number))
}
```

## TODO로 완성 강제하기

함수 구현을 완성하지 않으면 예외를 던지는 TODO 함수를 사용한다.

```kotlin
fun main() {
    // 실행 시 NotImplementedError 발
    TODO(reason = "none, really")
}

fun completeThis() {
    TODO()
}

internal fun `todo test`() {
    val exception = assertThrows<NotImplementedError> {
        TODO("seriously, finish this")
    }
    assertEquals("An operation is not implemented: seriously, finish this",
        exception.message)
}
```

## 자바에게 예외 알리기

코틀린의 모든 예외는 언체크 예외다. 즉 컴파일러는 개발자에게 해당 예외를 처리할 것을 요구하지 않는다. 코틀린에는 자바에서 메소드가 예외를 발생시킬지도 모른다고 선언할 때 사용하는 throws 키워드가 없다.

자바에서 코틀린 함수를 호출하기 전까지는 아무런 문제가 없다. 호출한 코틀린 함수가 잠재적으로 자바에서 체크 예외라고 여겨지는 예외를 던지고 자바에서 해당 예외를 잡고 싶다면 자바에게 해당 사실을 알려줘야 한다.

```kotlin
@Throws(IOException::class)
fun houstonWeHaveAProblem() {
    throw IOException("Nope")
}
```

자바 컴파일러는 @Throws 애노테이션을 통해 IOException을 대비해야 한다는 것을 안다. 물론 IOException은 체크 예외이기 때문에 더 이상 컴파일되지 않는다. @Throws 애노테이션은 그저 자바/코틀린 통합을 위해서 존재한다.

